services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - XENDIT_SECRET_KEY=${XENDIT_SECRET_KEY}
      - XENDIT_PUBLIC_KEY=${XENDIT_PUBLIC_KEY}
    depends_on:
      - db
    networks:
      - spoticket-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spoticket-network

volumes:
  postgres_data:

networks:
  spoticket-network:
    driver: bridge